// Rates live in two places: api/_rooms.js decides what a guest is charged, and
// index.html decides what they are shown. If those drift, the site quotes one
// price and takes another.
//
//   node scripts/check-rates.mjs
//
// Exits non-zero on a mismatch, so it can gate a deploy.

import { readFileSync } from 'fs';
import { createRequire } from 'module';

const require = createRequire(import.meta.url);
const { ROOMS } = require('../api/_rooms.js');
const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8');

function fail(msg) {
  console.error('  ' + msg);
  process.exitCode = 1;
}

// ROOM_PRICES = { comfort: 70, 'ground-floor': 80, ... }
const priceBlock = html.match(/const ROOM_PRICES = \{([^}]*)\}/);
if (!priceBlock) {
  console.error('Could not find ROOM_PRICES in index.html');
  process.exit(1);
}
const shown = {};
for (const m of priceBlock[1].matchAll(/'?([a-z-]+)'?\s*:\s*(\d+)/g)) {
  shown[m[1]] = Number(m[2]);
}

console.log('Comparing server rates with the page\n');

const serverKeys = Object.keys(ROOMS);
const shownKeys = Object.keys(shown);

for (const key of serverKeys) {
  if (!(key in shown)) { fail(`${key}: on the server but missing from the page`); continue; }
  if (shown[key] !== ROOMS[key].rate) {
    fail(`${key}: page shows $${shown[key]}, server charges $${ROOMS[key].rate}`);
  }
}
for (const key of shownKeys) {
  if (!(key in ROOMS)) fail(`${key}: on the page but the server will reject it as an unknown room`);
  else if (!Number.isInteger(ROOMS[key].capacity) || ROOMS[key].capacity <= 0) {
    fail(`${key}: page room does not have a positive integer server capacity`);
  }
}

// The structured data quotes prices too
const ld = html.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/);
if (ld) {
  try {
    const data = JSON.parse(ld[1]);
    for (const offer of data.makesOffer || []) {
      const match = Object.values(ROOMS).find(r => r.name === offer.name);
      if (!match) fail(`structured data offers "${offer.name}", which is not a room`);
      else if (Number(offer.price) !== match.rate) {
        fail(`structured data: "${offer.name}" at $${offer.price}, server charges $${match.rate}`);
      }
    }
  } catch {
    fail('structured data is not valid JSON');
  }
}

if (process.exitCode) {
  console.error('\nRates are out of step. Fix before deploying.');
} else {
  console.log(`  all ${serverKeys.length} rooms agree across the server, the page and the structured data`);
}

// ── room landing pages ────────────────────────────────────────────────────
// These are generated by scripts/build-rooms.mjs from the same table, but a
// price change with no rebuild would leave them quoting the old figure.
import { existsSync, readdirSync } from 'fs';
if (existsSync('rooms')) {
  const pages = readdirSync('rooms').filter((f) => f.endsWith('.html'));
  let checked = 0;
  for (const f of pages) {
    const page = readFileSync(`rooms/${f}`, 'utf8');
    const ld = page.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/);
    if (!ld) { fail(`rooms/${f}: no structured data`); continue; }
    let room;
    try {
      room = JSON.parse(ld[1])['@graph'].find((x) => x['@type'] === 'HotelRoom');
    } catch {
      fail(`rooms/${f}: structured data is not valid JSON`); continue;
    }
    if (!room) { fail(`rooms/${f}: no HotelRoom in the graph`); continue; }
    const match = Object.entries(ROOMS).find(([, r]) => r.name === room.name);
    if (!match) { fail(`rooms/${f}: "${room.name}" is not a room in api/_rooms.js`); continue; }
    const [, server] = match;
    const shown = Number(room.offers.price);
    if (shown !== server.rate) {
      fail(`rooms/${f}: page quotes $${shown}, server charges $${server.rate} — run node scripts/build-rooms.mjs`);
    }
    // the visible price, not only the schema
    if (!page.includes(`<strong>$${server.rate}</strong>`)) {
      fail(`rooms/${f}: the price on the page does not read $${server.rate}`);
    }
    checked++;
  }
  if (!process.exitCode) console.log(`  all ${checked} room pages quote the server's rate`);
}
